spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

    sentinel:
      transport:
        dashboard: 127.0.0.1:8333
        port: 8719

  application:
    name: doermail-search

  data:
    elasticsearch:
      cluster-nodes: 192.168.2.200:9300
      cluster-name: elasticsearch

  thymeleaf:
    cache: false

  # session配置redis连接
  redis:
    host: 192.168.2.200
    port: 6379
    jedis:
      pool:
        max-wait: -1
        max-idle: 50
        min-idle: 5
        max-active: 50
    timeout: 100000

  session:
    store-type: redis

  # 服务调用链追踪
  zipkin:
    base-url: http://localhost:9411  # zipkin服务器地址
    # 关闭服务发现，否则Spring Cloud会把zipkin的url当做服务名称
    discovery-client-enabled: false
    sender:
      type: web # 设置使用 http 的方式传输数据
  sleuth:
    sampler:
      probability: 1.0 # 设置抽样采集率为100%，默认为0.1，即10%


# ES中检索语句DSL打印
logging:
  level:
    org:
      springframework:
        data:
          elasticsearch:
            core: debug

server:
  port: 12000
