spring:
  datasource:
    username: root
    password: make1234
    url: jdbc:mysql://192.168.2.200:3306/gulimall_oms?rewriteBatchedStatements=true&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

    sentinel:
      transport:
        dashboard: 127.0.0.1:8333
        port: 8719

  application:
    name: doermail-order

  rabbitmq:
    host: 192.168.2.200
    port: 5672
    virtual-host: /
    # 开启发送端确认
    publisher-confirms: true
    # 开启发送端消息抵达队列的确认
    publisher-returns: true
    # 只要抵达队列以异步模式优先回调这个returnConfigrm
    template:
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual
    connection-timeout: 100000

  thymeleaf:
    cache: false

  redis:
    host: 192.168.2.200
    port: 6379
    jedis:
      pool:
        max-wait: -1
        max-idle: 50
        min-idle: 5
        max-active: 50
    timeout: 100000

  session:
    store-type: redis

  mvc:
    date-format: yyyy-MM-dd HH:mm:ss

  # 服务调用链追踪
  zipkin:
    base-url: http://localhost:9411  # zipkin服务器地址
    # 关闭服务发现，否则Spring Cloud会把zipkin的url当做服务名称
    discovery-client-enabled: false
    sender:
      type: web # 设置使用 http 的方式传输数据
  sleuth:
    sampler:
      probability: 1.0 # 设置抽样采集率为100%，默认为0.1，即10%

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto


server:
  port: 9000

doermall:
  thread:
    core-pool-size: 20
    max-pool-size: 200
    keep-alive-time: 10

# 支付宝相关的配置
alipay:
  app_id: 2021000117680586

# 该服务Feign远程调用其他服务熔断保护
feign:
  sentinel:
    enabled: true