spring:
  datasource:
    username: root
    password: make1234
    url: jdbc:mysql://192.168.2.200:3306/gulimall_pms?rewriteBatchedStatements=true&allowMultiQueries=true&autoReconnect=true
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

    sentinel:
      transport:
        dashboard: 127.0.0.1:8333
        port: 8719

#    alicloud:
#      access-key: LTAI5t75KXjVWjGJhxUsBZxv   # oss文件上传key
#      secret-key: N0ZiNdO6GEJQEKxZMmuHwTq2F8Fwg7 # oss文件上传密匙
#      oss:
#        endpoint: oss-cn-beijing.aliyuncs.com  # bucket名，oss文件上传到哪个容器

  application:
    name: doermail-product

# json字段返回时有日期字段的同一格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

  thymeleaf:
    cache: false

  redis:
    host: 192.168.2.200
    port: 6379
    jedis:
      pool:
        max-wait: -1
        max-idle: 50
        min-idle: 5
        max-active: 50
    timeout: 100000


  cache:
    type: redis
    redis:
      time-to-live: 3600000 # 毫秒单位
#      key-prefix: CACHE_ # 如果指定了前缀就用我们指定的前缀，如果没有就默认使用缓存的名字cacheNames作为前缀
      use-key-prefix: true # 是否使用缓存前缀
      cache-null-values: true # 是否缓存空值，防止缓存穿透问题

  session:
    store-type: redis

  # 服务调用链追踪
  zipkin:
    base-url: http://localhost:9411/  # zipkin服务器地址
    # 关闭服务发现，否则Spring Cloud会把zipkin的url当做服务名称
    discovery-client-enabled: false
    sender:
      type: web # 设置使用 http 的方式传输数据
  sleuth:
    sampler:
      probability: 1.0 # 设置抽样采集率为100%，默认为0.1，即10%

  main:
    allow-bean-definition-overriding: true

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  # @TableId默认为None，这里设置为自增主键
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

server:
  port: 10000

logging:
  level:
    com.lookstarry.doermail: info
    org.springframework.cloud.openfeign: debug
    org.springframework.cloud.sleuth: debug


feign:
  sentinel:
    enabled: false

  hystrix:
    enabled: true



#调用openfeign，hystrix的超时时间
hystrix:
  command:
    default:
      circuitBreaker:
        sleepWindowInMilliseconds: 300000
        forceClosed: true
      execution:
        timeout:
          enabled: false
        isolation:
          thread:
            timeoutInMilliseconds: 300000


# ribbon的超时时间
riboon:
  SocketTimeout: 300000
  ReadTimeout: 300000
  ConnectTimeout: 30000

doermall:
  thread:
    core-pool-size: 20
    max-pool-size: 200
    keep-alive-time: 10
