# 配置nacos服务注册地址
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  application:
    name: doermail-third-party

server:
  port: 30000

doermall:
  sms:
    appcode: c1774f94a64c432097cc01196c313501
    host: https://msg.market.alicloudapi.com
    path: /msg
    title: 云码通
    mouldno: 44CAD037

